# Generated by Django 4.2.6 on 2023-10-30 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp03', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('point', models.FloatField(default=0.0)),
                ('reserve', models.FloatField(default=0.0)),
            ],
        ),
    ]
